site_name: Opps Project
dev_addr: 0.0.0.0:8000
pages:
- Home: index.md
- Documentation:
  - Getting Started: documentation/getting-started.md
  - Content Architecture: documentation/content_architecture.md
  - General Packages: documentation/packages.md
  - Opps Plugins: documentation/opps-apps.md
- Configuration:
  - Core Settings: configuration/core.md
  - Cache: configuration/cache.md
  - Feed: configuration/feed.md
  - Customization: configuration/customization.md
  - Mobile: configuration/mobile.md
- Contribute:
  - How to contribute: contributing/how-to.md
  - Git tips: contributing/git-tips.md
  - The Opps team: contributing/team.md
